# RESPUESTAS A LAS PREGUNTAS {-}


:::quiz

## **¿Por qué es necesario establecer los usos inválidos de la prueba?** {#quiz1}

Para evitar que nuestro instrumento sea usado de forma indebida, y, por ende, haga inválidas las interpretaciones de la prueba. 

:::

:::quiz

## **¿Qué función tiene el propósito de la evaluación?** {#quiz2}

Será nuestra guía en la toma de decisiones durante todo el proceso de diseño, desarrollo, implementación e interpretación de la prueba.

:::

:::quiz

## **¿Para qué necesitamos un marco conceptual del constructo a evaluar?** {#quiz3}

Para usarlo como una base teórica sobre la cual construir nuestro examen, generando evidencias de validez de la interpretación del examen. 

:::

:::quiz

## **¿Cuál es la utilidad que tiene generar una tabla de especificaciones?** {#quiz4}
 
La tabla de especificaciones cumple dos propósitos principales. Nos sirve como una guía clara y concisa para el proceso de diseño de reactivos, de manera que expertos en el tema ajenos al proceso previo de diseño del examen, puedan comenzar a generar reactivos con solo guiarse con la tabla de especificaciones. Por otro lado, sirve como un registro del proceso de operacionalización, lo que nos da evidencia de la validez de las interpretaciones del examen.

:::

:::quiz

## **¿Cuál es la importancia de utilizar diferentes grupos de expertos en la revisión de los reactivos?** {#quiz5}

Hay muchos aspectos que se deben cuidar para que no intervengan y afecten el constructo que queremos medir, de otra manera las interpretaciones que hagamos de los resultados y usos de la prueba no serán válidos y podrían traer consecuencias negativas para los sustentantes, por lo que los reactivo deben pasar por una revisión profunda antes de ser aplicados.

:::

:::quiz

## **¿Por qué es ideal realizar un piloteo de los reactivos?** {#quiz6}

Porque nos permite determinar los errores que podemos cometer en la administración del examen y obtener los parámetros psicométricos de los reactivos para determinar cuáles son adecuados para medir el constructo de interés y así poder ensamblar el examen o las diferentes versiones de este. 

:::

